; PlatformIO Project Configuration File
;
; Version numbers for releases are automatically applied by GitHub
; during the release build process based on the tag associated with
; the GitHub release.

; To ensure builds work correctly in GitHub the default_envs
; should always be set to all supported MobiFlight platforms.
; If you want to only build a single platform locally during
; development use VSCode to change the target to a non-default
; by clicking on the target name in the bottom status bar.
[platformio]
extra_configs = ./**/*platformio.ini

; Common build settings across all devices
[env]
lib_deps = 
	https://github.com/MobiFlight/Arduino-CmdMessenger#4.2.1
custom_lib_deps_Atmel =
build_flags =
	-DMF_REDUCE_FUNCT_LEDCONTROL
	-DMAXCALLBACKS=35
	-DSERIAL_RX_BUFFER_SIZE=32
	-DMESSENGERBUFFERSIZE=32
	-DMAXSTREAMBUFFERSIZE=32
	-DDEFAULT_TIMEOUT=5000
	-DDEBUG2CMDMESSENGER

     ; --- Features EINSCHALTEN (=1) ---
    -D MF_CUSTOMDEVICE_SUPPORT=1   ; Für dein OLED
    -D MF_BUTTON_SUPPORT=1         ; Für deine Schalter-Matrix & Encoder-Buttons
    -D MF_ENCODER_SUPPORT=1        ; <--- WICHTIG: Für deine Drehregler!

	-I./src/src
	-I./src/src/MF_Analog
	-I./src/src/MF_Button
	-I./src/src/MF_Encoder
	-I./src/src/MF_InputShifter
	-I./src/src/MF_DigInMux
	-I./src/src/MF_LCDDisplay
	-I./src/src/MF_Output
	-I./src/src/MF_OutputShifter
	-I./src/src/MF_Segment
	-I./src/src/MF_Servo
	-I./src/src/MF_Stepper
	-I./src/src/MF_Modules
build_src_filter =
	+<*>
extra_scripts =
	pre:get_version.py
	pre:get_CoreFiles.py
	copy_fw_files.py
